version: '2'
services:
  # ====================================================================================================================
  neo4j:
    image: straumat/bci-neo4j-docker-with-data:1.0
    # If you want persistent data, uncomment those lines to map your local folder.
    #volumes:
      #- ./data/neo4j:/var/lib/neo4j/data
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/b2g135!
  # ====================================================================================================================
