version: '2'
services:
  # ====================================================================================================================
  # Blockchain2graph.
  blockchain2graph:
    image: straumat/blockchain2graph:2.1-SNAPSHOT
    volumes:
      - /opt/tmp:/var/lib/neo4j/data
    ports:
      - 7474:7474
      - 7687:7687
      - 8080:8080
  # ====================================================================================================================
  # bci-ai-runner.
